version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      # The SECRET_KEY will be generated at runtime in the production.py file
    restart: always
